# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



# Build settings
markdown: kramdown
#theme: twister_theme
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

  

future: true
  
title: 1000 Possible Worlds
name: 1000 Possible Worlds
author: Jim
description: A collection of media by Jim Hays; recordings and writings.
url: #place url # the base hostname & protocol for your site, e.g. http://example.com
baseurl: #place folder name if site is served in subfolder # the subpath of your site, e.g. /blog

permalink: /:title/
paginate: 20
paginate_path: /page/:num/
tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'By '
media_folder: /img
author_default_avatar: /profile-pic.jpg
#tumblr: "#"
#pinterest: "#"
#instagram: "#"
email: calvinballing@gmail.com
twitter_username: calvinballing
github_username:  calvinballing
#facebook: "#"
#youtube: "#"
#vimeo: "#"
#soundcloud: "#"

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, documentation, vendor]

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "display post at full width or with sidebar"
          options:
            - name: "with sidebar"
              value: "post"
            - name: "full width"
              value: "post_full"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "author id as defined within _data/authors.yml"
          type: "text"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Post Type"
          help: "each type has some special feature"
          options:
            - name: "Standard"
              value: "standard"
            - name: "Image"
              value: "image"
            - name: "Gallery"
              value: "gallery"
            - name: "Audio"
              value: "audio"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Set post type to vimeo in order for this to work"
      - name: "gallery-id"
        field:
          element: "text"
          label: "Gallery ID"
          help: "ID of the gallery defined within _data/galleries.yml - use include in content to use"
      - name: "audio-embed"
        field:
          element: "text"
          label: "Audio Embedding Code"
          help: "Set post type to audio in order for this to work"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"

