# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
markdown: kramdown
#theme: twister_theme
plugins:
  - jekyll-feed
  - jekyll-postcss-v2
  - jekyll-archives
  - jekyll-webp
postcss:
  cache: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

future: true

title: The Corollary Zone
name: The Corollary Zone
author: Jim
description: A collection of projects by Jim Hays
url: #place url # the base hostname & protocol for your site, e.g. http://example.com
baseurl: #place folder name if site is served in subfolder # the subpath of your site, e.g. /blog

permalink: /:title/
paginate: 12
paginate_path: /page/:num/
tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'By '
media_folder: img
author_default_avatar: /profile-pic.jpg
email: calvinballing@gmail.com
twitter: https://twitter.com/calvinballing
github_username:  calvinballing
github: [metadata]
repository: calvinballing/calvinballing.github.io
#youtube: "#"
#soundcloud: "#"

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, documentation, vendor]

responsive_image:
  template: _includes/responsive_image.html
  sizes:
    - width: 320
    - width: 480
    - width: 960

jekyll-archives:
  enabled:
    - tags
  layout: tag_index
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/img", "/assets/resized"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp" # cspell:ignore cwebp
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################